version: '3.8'

services:
  web:
    image: laravel-docker/web
    container_name: web
    build:
      context: ./docker/web
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT:-80}:80
    volumes:
      - .:/var/www/html
    networks:
      - ldsnet
  node:
    image: node:14
    container_name: node
    volumes:
      - .:/var/www/html
    ports:
      - ${NODE_PORT:-3000}:3000
      - ${NODE_PORT_ALT:-3001}:3001
    working_dir: /var/www/html
    entrypoint: bash -c "npm install && npm run watch"
    networks:
      - ldsnet
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - redisdata:/data
    networks:
      - ldsnet
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - ${DB_PORT:-3306}:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
     - mysqldata:/var/lib/mysql
    networks:
     - ldsnet
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - ${MAILHOG_SMTP_PORT:-1025}:1025
      - ${MAILHOG_HTTP_PORT:-8025}:8025
    networks:
      - ldsnet
networks:
  ldsnet:
    driver: bridge
volumes:
  mysqldata:
    driver: local
  redisdata:
    driver: local