name: Laravel Sync

on:
  schedule:
    - cron: "17 * * * *"

  workflow_dispatch:

jobs:
  sync:
    env:
      laravel_version: $(curl -Ls https://api.github.com/repos/laravel/laravel/tags | jq -r '.[0].name')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Sync Latest Laravel
        run: |
          echo "Checking Laravel repo..."
          curl -Ls --time-cond ./artisan --remote-time https://api.github.com/repos/laravel/laravel/tarball -o laravel.tar
          if [ -f ./laravel.tar ]; then
            echo "Extracting and updating repo files..."
            find . -maxdepth 1 ! -name .git ! -name .github ! -name .gitignore ! -name laravel.tar ! -name "docker" ! -name "cmd" ! -name "docker-compose.yml" ! -name . -exec rm -r {} \; && tar xzf ./laravel.tar --strip-components 1 && sed -i -e 's/^DB_HOST.*$/DB_HOST=mysql/g' ".env.example" && sed -i -e 's/^REDIS_HOST.*$/REDIS_HOST=redis/g' ".env.example" && rm laravel.tar

            if git show-ref --tags ${{ env.laravel_version }} --quiet; then
              echo "Tag ${{ env.laravel_version }} exists."
            else
              echo "Updating files to ${{ env.laravel_version }}"
              git config user.name github-actions
              git config user.email github-actions@github.com
              git add .
              git commit -m "Auto-update Laravel ${{ env.laravel_version }}"
              git tag ${{ env.laravel_version }}
              git push --atomic origin master ${{ env.laravel_version }}
            fi
          else
            echo "No updates available."
          fi