name: Laravel Sync

on:
  schedule:
    - cron: "17 * * * *"

  workflow_dispatch:

jobs:
  sync:
    env:
      current_version: $(curl -Ls https://api.github.com/repos/ractoon/laravel-docker/tags | jq -r '.[0].name')
      laravel_version: $(curl -Ls https://api.github.com/repos/laravel/laravel/tags | jq -r '.[0].name')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Sync Latest Laravel
        run: |
          echo "Checking Laravel repo..."
          if [[ "${{ env.current_version }}" != "${{ env.laravel_version }}" ]]; then
            curl -Ls https://api.github.com/repos/laravel/laravel/tarball -o ${{ runner.temp }}/laravel.tar
            echo "Extracting and updating repo files..."
            find . -maxdepth 1 ! -name .git ! -name .github ! -name .gitignore ! -name laravel.tar ! -name "docker" ! -name "cmd" ! -name "docker-compose.yml" ! -name . -exec rm -r {} \; && tar xzf ${{ runner.temp }}/laravel.tar --strip-components 1 --exclude='README.md' -C . && sed -i -e 's/^DB_HOST.*$/DB_HOST=mysql/g' ".env.example" && sed -i -e 's/^REDIS_HOST.*$/REDIS_HOST=redis/g' ".env.example"

            if git show-ref --tags "${{ env.laravel_version }}" --quiet; then
              echo "Tag ${{ env.laravel_version }} exists."
            else
              echo "Updating files to ${{ env.laravel_version }}"
              git config user.name github-actions
              git config user.email github-actions@github.com
              git add .
              if [[ `git diff-index --quiet HEAD --` ]]; then
                echo "Committing changes..."
                git commit -m "Auto-update Laravel ${{ env.laravel_version }}"
                git tag ${{ env.laravel_version }}
                git push --atomic origin master ${{ env.laravel_version }}
              else
                echo "No changes to commit."
              fi
            fi
          else
            echo "Up to date."
          fi
