name: Laravel Sync

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  sync:
    env:
      laravel_version: $(curl -Ls https://api.github.com/repos/laravel/laravel/tags | jq -r '.[0].name')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Sync Latest Laravel
        run: |
          curl -Ls --time-cond ./artisan --remote-time https://api.github.com/repos/laravel/laravel/tarball -o laravel.tar
          [ -f ./laravel.tar ] && find . -maxdepth 1 ! -name .git ! -name .gitignore ! -name laravel.tar ! -name "docker" ! -name "cmd" ! -name "docker-compose.yml" ! -name . -exec rm -r {} \; && tar xzf ./laravel.tar --strip-components 1 && sed -i '' 's/^DB_HOST.*$/DB_HOST=mysql/g' .env.example && sed -i '' 's/^REDIS_HOST.*$/REDIS_HOST=redis/g' .env.example && rm laravel.tar
          echo "::set-env name=laravel_version::$(curl -Ls https://api.github.com/repos/laravel/laravel/tags | jq -r '.[0].name')"

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Update Laravel ${{ env.laravel_version }}
          tagging_message: ${{ env.laravel_version }}